name = "relatoria-extrema-pobreza-web"
compatibility_date = "2026-07-27"

[assets]
directory = "./dist"
html_handling = "force-trailing-slash"

[vars]
PUBLIC_SITE_URL = "https://srextremepovertyhr.org"
